{
 "title": "Interface Panel",
 "tags": [
  "interfaces",
  "nsgv2.4"
 ],
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SELECT name FROM devices WHERE Role != NetSpyGlassServer AND Role != SimulatedNode AND Role != SimulatedBridge ORDER BY name"
   },
   {
    "name": "interface",
    "query": "SELECT component FROM ifOperStatus WHERE device=\"$device\" ORDER BY component"
   }
  ]
 },
 "panels": [
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "deviceName",
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "Model",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "SerialNumber",
        "visible": true
       },
       {
        "alias": "uptime",
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "Vendor",
        "visible": true
       }
      ],
      "disableAdHoc": false,
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": true,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" }
      ],
      "type": "nsgql",
      "variable": "sysUpTime"
     },
     "category": "SNMP",
     "columns": "sysUpTime,Vendor,Model,SerialNumber",
     "component": "select component",
     "device": "$device",
     "formatDisplay": "Table",
     "group": "select group",
     "limit": "1",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "sysUpTime"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "component",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "ifAdminStatus",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "ifOperStatus",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "Link",
        "visible": true
       },
       {
        "appliedFunctions": [],
        "name": "description",
        "visible": true
       }
      ],
      "disableAdHoc": false,
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": true,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifOperStatus"
     },
     "aggregator": " -- ",
     "category": "Interface",
     "columns": "ifAdminStatus,ifOperStatus,description",
     "component": "$component",
     "device": "$deviceName",
     "formatDisplay": "Table",
     "group": "select group",
     "limit": "1",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "ifOperStatus"
    }
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device:$component",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifInRate"
     },
     "aggregator": " -- ",
     "alias": "$device / $component [$description]",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifInRate",
     "query": "SELECT last(\"value\") FROM \"ifInRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifInRate"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifOutRate"
     },
     "alias": "$device / $component",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifOutRate",
     "query": "SELECT last(\"value\") FROM \"ifOutRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifOutRate"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifInErrorRate"
     },
     "alias": "$device / $component",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifInErrorRate",
     "query": "SELECT last(\"value\") FROM \"ifInErrorRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifInErrorRate"
    }
   ]
  },
  {
   "title": "Outbound Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifOutErrorRate"
     },
     "alias": "$device / $component",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifOutErrorRate",
     "query": "SELECT last(\"value\") FROM \"ifOutErrorRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifOutErrorRate"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Discards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifInDiscardRate"
     },
     "alias": "$device / $component",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifInDiscardRate",
     "query": "SELECT last(\"value\") FROM \"ifInDiscardRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifInDiscardRate"
    }
   ]
  },
  {
   "title": "Outbound Discards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "$device" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$interface" }
      ],
      "type": "nsgql",
      "variable": "ifOutDiscardRate"
     },
     "alias": "$device / $component",
     "category": "Interface",
     "columns": "time,variable,device,component,metric",
     "component": "/^$component$/",
     "device": "$device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": -1,
     "measurement": "ifOutDiscardRate",
     "query": "SELECT last(\"value\") FROM \"ifOutDiscardRate\" WHERE \"deviceName\" = '$deviceName' AND \"component\" = '$component' AND $timeFilter GROUP BY time($interval), \"deviceName\", \"component\" fill(null)",
     "resultFormatDisplay": "Time Series",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/$deviceName$/" },
      { "condition": "AND", "key": "component", "operator": "=~", "value": "/$component$/" }
     ],
     "variable": "ifOutDiscardRate"
    }
   ]
  }
 ]
}