{
 "title": "NSG Self-Monitoring",
 "tags": [
  "self-monitoring",
  "nsgv2.2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Process Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "alias": "version",
        "appliedFunctions": [],
        "name": "nsgVersion",
        "visible": true
       },
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": true,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "processUptime"
     },
     "aggregator": " -- ",
     "category": "Monitor",
     "columns": "device,metric,nsgVersion",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Table",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "descending",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "processUptime"
    }
   ]
  },
  {
   "title": "Server Free Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "freeTime"
     },
     "aggregator": " -- ",
     "alias": "$device",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "freeTime",
     "query": "SELECT mean(\"value\") FROM \"freeTime\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time(1h), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "selector": " -- ",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
     ],
     "variable": "freeTime"
    }
   ]
  },
  {
   "title": "Number of allocated devices",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numDevices"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numDevices"
    }
   ]
  },
  {
   "title": "Number of variables",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numVars"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numVars"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": true,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numDevices"
     },
     "aggregator": " -- ",
     "category": "Monitor",
     "columns": "device,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Table",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "numDevices",
     "query": "SELECT last(\"value\") FROM \"numDevices\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numDevices"
    }
   ]
  },
  {
   "title": "Variables",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": true,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numVars"
     },
     "aggregator": " -- ",
     "category": "Monitor",
     "columns": "device,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Table",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "numVars",
     "query": "SELECT last(\"value\") FROM \"numVars\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numVars"
    }
   ]
  },
  {
   "title": "Last Contact Time",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": true,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "Role", "operator": "=", "value": "NetSpyGlassServer" }
      ],
      "type": "nsgql",
      "variable": "timeSinceLastContact"
     },
     "aggregator": " -- ",
     "category": "Status",
     "columns": "device,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Table",
     "group": "select group",
     "limit": "20",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" },
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "lastContactTime"
    }
   ]
  },
  {
   "title": "Time since last discovery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 1,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "timeSinceLastDiscovery"
     }
    }
   ]
  },
  {
   "title": "UI Web Server Responses (resp/sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "2xx",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "device", "operator": "=", "value": "PrimaryServer" }
      ],
      "type": "nsgql",
      "variable": "webServerResponses2xxRate"
     },
     "aggregator": " -- ",
     "alias": "5xx",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "webServerResponses5xxRate"
    },
    {
     "_nsgTarget": {
      "alias": "3xx",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "device", "operator": "=", "value": "PrimaryServer" }
      ],
      "type": "nsgql",
      "variable": "webServerResponses3xxRate"
     },
     "alias": "200",
     "columns": [
      {
       "appliedFunctions": [],
       "name": "metric",
       "visible": true
      },
      {
       "name": "time",
       "visible": false
      }
     ],
     "groupBy": { "type": "select type", "value": "select value" },
     "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
     "tags": [
      { "key": "device", "operator": "=", "value": "PrimaryServer" }
     ],
     "type": "nsgql",
     "variable": "webServerResponses2xxRate"
    },
    {
     "_nsgTarget": {
      "alias": "4xx",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "C",
      "tags": [
       { "key": "device", "operator": "=", "value": "PrimaryServer" }
      ],
      "type": "nsgql",
      "variable": "webServerResponses4xxRate"
     }
    },
    {
     "_nsgTarget": {
      "alias": "5xx",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "D",
      "tags": [
       { "key": "device", "operator": "=", "value": "PrimaryServer" }
      ],
      "type": "nsgql",
      "variable": "webServerResponses5xxRate"
     }
    }
   ]
  },
  {
   "title": "NSGQL queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "nsgqlOutstandingQueries"
     },
     "aggregator": " -- ",
     "alias": "5xx",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "webServerResponses5xxRate"
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "maxNsgqlOutstandingQueries"
     },
     "aggregator": " -- ",
     "alias": "5xx",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "webServerResponses5xxRate"
    }
   ]
  },
  {
   "title": "Database",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "c3p0NumConnections"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "cpuUsage",
     "query": "SELECT last(\"value\") FROM \"cpuUsage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "cpuUsage"
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "c3p0NumBusyConnections"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "cpuUsage",
     "query": "SELECT last(\"value\") FROM \"cpuUsage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "cpuUsage"
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "C",
      "tags": [],
      "type": "nsgql",
      "variable": "c3p0FailedCheckoutsRate"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "cpuUsage",
     "query": "SELECT last(\"value\") FROM \"cpuUsage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "cpuUsage"
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "D",
      "tags": [],
      "type": "nsgql",
      "variable": "c3p0FailedIdleTestsRate"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "cpuUsage",
     "query": "SELECT last(\"value\") FROM \"cpuUsage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "cpuUsage"
    }
   ]
  },
  {
   "title": "TSDB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbVarCount"
     }
    }
   ]
  },
  {
   "title": "TSDB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbSaveTime"
     }
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "C",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbSaverQueueSize"
     }
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbSenderQueueSize"
     }
    }
   ]
  },
  {
   "title": "TSDB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbSaveLag"
     }
    },
    {
     "_nsgTarget": {
      "alias": "$variable",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "C",
      "tags": [],
      "type": "nsgql",
      "variable": "tsDbTimeSinceLastSave"
     }
    }
   ]
  },
  {
   "title": "Python Hook Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "pythonErrorsRate"
     },
     "aggregator": " -- ",
     "alias": "$device",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "pythonErrorsRate"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "conf.alerts: $device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "Role", "operator": "=", "value": "NetSpyGlassServer" }
      ],
      "type": "nsgql",
      "variable": "numAlerts"
     },
     "aggregator": " -- ",
     "alias": "$variable",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "nsg-alert_sjc12a-rd14-5a",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numActiveAlerts"
    },
    {
     "_nsgTarget": {
      "alias": "active alerts: $device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "Role", "operator": "=", "value": "NetSpyGlassServer" }
      ],
      "type": "nsgql",
      "variable": "numActiveAlerts"
     },
     "aggregator": " -- ",
     "alias": "$variable",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "nsg-alert_sjc12a-rd14-5a",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numAlerts"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 }, "content": "# System\n" },
  {
   "title": "System (cpu)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "cpuUsage"
     }
    }
   ]
  },
  {
   "title": "System (memory)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "systemMemFreePercent"
     }
    }
   ]
  },
  {
   "title": "Process (opened file descriptors)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "openFdCount"
     }
    }
   ]
  },
  {
   "title": "Process (process memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "procMem"
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 }, "content": "# jvm" },
  {
   "title": "JVM used memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "jvmMemUsed"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "jvmMemTotal",
     "query": "SELECT last(\"value\") FROM \"jvmMemTotal\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
     ],
     "variable": "jvmMemUsed"
    }
   ]
  },
  {
   "title": "JVM Free Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "jvmMemFree"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "jvmMemFree",
     "query": "SELECT last(\"value\") FROM \"jvmMemFree\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
     ],
     "variable": "jvmMemFree"
    }
   ]
  },
  {
   "title": "GC Count rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "GCCountRate"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "GCCountRate",
     "query": "SELECT last(\"value\") FROM \"GCCountRate\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "GCCountRate"
    }
   ]
  },
  {
   "title": "GC Time rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s", "label": "GCTime" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [],
      "type": "nsgql",
      "variable": "GCTimeRate"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRole)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "GCTimeRate",
     "query": "SELECT last(\"value\") FROM \"GCTimeRate\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "GCTimeRate"
    }
   ]
  }
 ]
}