# config file version
apiVersion: 1

## list of datasources that should be deleted from the database
#deleteDatasources:
#  - name: Graphite
#    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: "NetSpyGlass-v2"
  # <string, required> datasource type. Required
  type: "happygears-netspyglass-datasource-v2"
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: "http://nsg_svc:9100"
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     accessToken: "jk132bQlp"
     networkId: 1
     tlsSkipVerify: true
     useToken: true
#  # <string> json object of data that will be encrypted.
#  secureJsonData:
#    tlsCACert: "..."
#    tlsClientCert: "..."
#    tlsClientKey: "..."
#  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false
