version: '3.8'

services:
  grafana:
    user: root
    container_name: 'happygears-netspyglass-datasource-v2'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3001:3000/tcp
    volumes:
      - "grafana-data:/var/lib/grafana"
      - ../dist:/var/lib/grafana/plugins/happygears-netspyglass-datasource-v2
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/happygears-netspyglass-datasource-v2

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.happygears-netspyglass-datasource-v2:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: happygears-netspyglass-datasource-v2