{
 "title": "NSG Self-Monitoring",
 "tags": [
  "self-monitoring",
  "nsgv2.2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "NsgRole",
    "query": "aggregator,agent,monitor,manager"
   },
   {
    "name": "region",
    "query": "SELECT DISTINCT NsgRegion FROM numVars ORDER BY NsgRegion"
   }
  ]
 },
 "panels": [
  { "title": "NetSpyGlass", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 1,
      "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "physicalDevices"
     }
    }
   ]
  },
  {
   "title": "agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "NsgRegion",
        "visible": true
       },
       {
        "alias": "",
        "appliedFunctions": [
         { "name": "count" }
        ],
        "name": "device",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "column", "value": "NsgRegion" },
      "isTablePanel": true,
      "limit": 100,
      "nsgqlString": "SELECT device,NsgRegion FROM processUptime WHERE (NsgRole = 'agent') AND $_timeFilter LIMIT 100, 0",
      "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "agent" }
      ],
      "type": "nsgql",
      "variable": "processUptime"
     }
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "combinedNsgRoles",
        "visible": true
       },
       {
        "alias": "count",
        "appliedFunctions": [
         { "name": "count" }
        ],
        "name": "device",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "column", "value": "combinedNsgRoles" },
      "isTablePanel": true,
      "limit": 100,
      "orderBy": {
       "colName": "select value",
       "colValue": "select value",
       "column": {},
       "sort": "ASC"
      },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "Role", "operator": "=", "value": "NetSpyGlassServer" },
       { "condition": "AND", "key": "NsgRole", "operator": "!=", "value": "agent" }
      ],
      "type": "nsgql",
      "variable": "processUptime"
     }
    }
   ]
  },
  {
   "title": "Time since last discovery",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": false,
      "limit": 1,
      "loading": false,
      "orderBy": { "colName": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "manager" }
      ],
      "type": "nsgql",
      "variable": "timeSinceLastDiscovery"
     }
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "_nsgTarget": {
      "columns": [
       {
        "appliedFunctions": [],
        "name": "device",
        "visible": true
       },
       {
        "alias": "version",
        "appliedFunctions": [],
        "name": "SoftwareRev",
        "visible": true
       },
       {
        "appliedFunctions": [
         { "name": "tslast" }
        ],
        "name": "metric",
        "visible": true
       }
      ],
      "format": "table",
      "groupBy": { "type": "select type", "value": "select value" },
      "isTablePanel": true,
      "limit": 100,
      "loading": false,
      "nsgqlString": "SELECT device,SoftwareRev as `version`,tslast(metric) as `tslast_metric` FROM processUptime WHERE (NsgRole = 'aggregator') AND $_timeFilter ORDER BY `device` DESC LIMIT 100, 0",
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "alias": "", "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "processUptime"
     },
     "aggregator": " -- ",
     "category": "Monitor",
     "columns": "device,metric,nsgVersion",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Table",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "descending",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "processUptime"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "processUptime"
     }
    }
   ]
  },
  {
   "title": "Number of monitored devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "monitoredDevices"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numDevices"
    },
    {
     "_nsgTarget": {
      "alias": "total",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "sum" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": {
       "colName": "select value",
       "colValue": "select value",
       "column": {},
       "sort": "DESC"
      },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "monitoredDevices"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numDevices"
    }
   ]
  },
  {
   "title": "Agent and Server Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device - $component: total",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "D",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "lagTotal"
     },
     "aggregator": " -- ",
     "alias": "$device",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "freeTime",
     "query": "SELECT mean(\"value\") FROM \"freeTime\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time(1h), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "selector": " -- ",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "tags": [
      { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
     ],
     "variable": "freeTime"
    }
   ]
  },
  {
   "title": "monitoring variables metadata",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device - $component: size",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "manager" }
      ],
      "type": "nsgql",
      "variable": "metadataSize"
     }
    },
    {
     "_nsgTarget": {
      "alias": "$device - $component: misses",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" },
       { "condition": "AND", "key": "component", "operator": "=", "value": "$region" }
      ],
      "type": "nsgql",
      "variable": "metadataMissCount"
     }
    }
   ]
  },
  {
   "title": "Number of variables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "numVars"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numVars"
    },
    {
     "_nsgTarget": {
      "alias": "total",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "sum" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "loading": false,
      "orderBy": {
       "colName": "select value",
       "colValue": "select value",
       "column": {},
       "sort": "DESC"
      },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "numVars"
     },
     "aggregator": " -- ",
     "alias": "$device ($NsgRegion)",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "select device",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": "choose selector",
     "sortByEl": "none",
     "tagData": [
      { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
      { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
     ],
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numVars"
    }
   ]
  },
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python Hook Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "pythonErrorsRate"
       },
       "aggregator": " -- ",
       "alias": "$device",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "limit": "100",
       "selector": " -- ",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "variable": "pythonErrorsRate"
      }
     ]
    }
   ]
  },
  {
   "title": "NsgQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of NSGQL queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - $variable",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "disableAdHoc": false,
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [],
        "type": "nsgql",
        "variable": "nsgqlQueryRate"
       },
       "aggregator": " -- ",
       "alias": "5xx",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "limit": "100",
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "variable": "webServerResponses5xxRate"
      }
     ]
    },
    {
     "title": "Outstanding NSGQL queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - $variable",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "disableAdHoc": false,
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [],
        "type": "nsgql",
        "variable": "maxNsgqlOutstandingQueries"
       },
       "aggregator": " -- ",
       "alias": "5xx",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "limit": "100",
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "variable": "webServerResponses5xxRate"
      }
     ]
    },
    {
     "title": "NsgQL Indexer Queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "disableAdHoc": false,
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "device" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [],
        "type": "nsgql",
        "variable": "nsgqlIndexUpdateQueue"
       }
      }
     ]
    },
    {
     "title": "NsgQL Schema Updater Queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "disableAdHoc": false,
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "device" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [],
        "type": "nsgql",
        "variable": "nsgqlDynamicSchemaUpdateQueue"
       }
      }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Evaluated Alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device - conf.alerts",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "numAlerts"
     },
     "aggregator": " -- ",
     "alias": "$variable",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "nsg-alert_sjc12a-rd14-5a",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numActiveAlerts"
    },
    {
     "_nsgTarget": {
      "alias": "total",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "sum" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "numAlerts"
     },
     "aggregator": " -- ",
     "alias": "$variable",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "nsg-alert_sjc12a-rd14-5a",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numActiveAlerts"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device - active alerts",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": "",
      "loading": false,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "B",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "numActiveAlerts"
     },
     "aggregator": " -- ",
     "alias": "$variable",
     "category": "Monitor",
     "columns": "time,variable,device,component,metric",
     "component": "select component",
     "device": "nsg-alert_sjc12a-rd14-5a",
     "formatDisplay": "Time Series",
     "group": "select group",
     "limit": "100",
     "selector": " -- ",
     "sortByEl": "none",
     "tagFacet": "---",
     "tagOperation": "==",
     "tagWord": "---",
     "variable": "numAlerts"
    }
   ]
  },
  {
   "title": "Insensitive Alerts (per cycle)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numInsensitiveAlerts"
     }
    }
   ]
  },
  {
   "title": "TSDB Backfill Calls (per cycle)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "select type", "value": "select value" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [],
      "type": "nsgql",
      "variable": "numBackfillCalls"
     }
    }
   ]
  },
  {
   "title": "Alerts Lag",
   "type": "graph",
   "description": "Interval of time between beginning of the cycle and the time when alert computation finishes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "lagAlerts"
     }
    }
   ]
  },
  {
   "title": "Alerts Compute Time",
   "type": "graph",
   "description": "Time it takes to compute all alerts, per server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "_nsgTarget": {
      "alias": "$device",
      "columns": [
       {
        "appliedFunctions": [
         { "name": "tsavg" }
        ],
        "name": "metric",
        "visible": true
       },
       {
        "name": "time",
        "visible": false
       }
      ],
      "disableAdHoc": false,
      "format": "time_series",
      "groupBy": { "type": "time", "value": "$_interval" },
      "isMultiColumnMode": true,
      "isSeparatedColumns": false,
      "isTablePanel": false,
      "limit": 100,
      "orderBy": { "colName": "device", "colValue": "select value", "column": { "name": "device", "value": "device" }, "sort": "DESC" },
      "rawQuery": 0,
      "refId": "A",
      "tags": [
       { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
      ],
      "type": "nsgql",
      "variable": "computeTimeAlerts"
     }
    }
   ]
  },
  {
   "title": "Jetty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "UI Web Server Responses (resp/sec)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - requests",
        "columns": [
         {
          "appliedFunctions": [
           { "name": "tsavg" }
          ],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "time", "value": "$_interval" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "webServerRequestsRate"
       },
       "aggregator": " -- ",
       "alias": "5xx",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "limit": "100",
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "variable": "webServerResponses5xxRate"
      },
      {
       "_nsgTarget": {
        "alias": "$device - 5xx",
        "columns": [
         {
          "appliedFunctions": [
           { "name": "tsavg" }
          ],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "time", "value": "$_interval" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "D",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "webServerResponses5xxRate"
       }
      }
     ]
    },
    {
     "title": "UI Web Server Sessions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - web sessions",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "webServerSessions"
       },
       "aggregator": " -- ",
       "alias": "5xx",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "limit": "100",
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "primary" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "variable": "webServerResponses5xxRate"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - $variable",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "loading": false,
        "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "c3p0NumConnections"
       },
       "aggregator": " -- ",
       "alias": "$device ($NsgRole)",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "cpuUsage",
       "query": "SELECT last(\"value\") FROM \"cpuUsage\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "tags": [
        { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
       ],
       "variable": "cpuUsage"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "System (cpu)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "cpuUsage"
       }
      }
     ]
    },
    {
     "title": "Available system memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": 100,
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "systemMemFreePercent"
       }
      }
     ]
    },
    {
     "title": "Process (opened file descriptors)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "openFdCount"
       }
      }
     ]
    },
    {
     "title": "Process (process memory)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "procMem"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM used memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "jvmMemUsed"
       },
       "aggregator": " -- ",
       "alias": "$device ($NsgRole)",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "jvmMemTotal",
       "query": "SELECT last(\"value\") FROM \"jvmMemTotal\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "tags": [
        { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
       ],
       "variable": "jvmMemUsed"
      }
     ]
    },
    {
     "title": "JVM Free Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "alias": "", "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "jvmMemFree"
       },
       "aggregator": " -- ",
       "alias": "$device ($NsgRole)",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "jvmMemFree",
       "query": "SELECT last(\"value\") FROM \"jvmMemFree\" WHERE \"Role.NetSpyGlassServer\" = '1' AND $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "tags": [
        { "key": "Role.NetSpyGlassServer", "operator": "=", "value": "1" }
       ],
       "variable": "jvmMemFree"
      }
     ]
    },
    {
     "title": "GC Count rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "GCCountRate"
       },
       "aggregator": " -- ",
       "alias": "$device ($NsgRole)",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "GCCountRate",
       "query": "SELECT last(\"value\") FROM \"GCCountRate\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "tags": [
        { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
       ],
       "variable": "GCCountRate"
      }
     ]
    },
    {
     "title": "GC Time rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "GCTime" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isSeparatedColumns": false,
        "isTablePanel": false,
        "limit": "",
        "loading": false,
        "orderBy": { "colName": "column", "colValue": "device", "column": { "name": "column", "value": "column" }, "sort": "DESC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "GCTimeRate"
       },
       "aggregator": " -- ",
       "alias": "$device ($NsgRole)",
       "category": "Monitor",
       "columns": "time,variable,device,component,metric",
       "component": "select component",
       "device": "select device",
       "formatDisplay": "Time Series",
       "group": "select group",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "GCTimeRate",
       "query": "SELECT last(\"value\") FROM \"GCTimeRate\" WHERE $timeFilter GROUP BY time($interval), \"deviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "selector": "choose selector",
       "sortByEl": "none",
       "tagData": [
        { "tagFacet": "NsgRegion", "tagOperation": "==", "tagWord": "$region" },
        { "tagFacet": "NsgRole", "tagOperation": "==", "tagWord": "$role" }
       ],
       "tagFacet": "---",
       "tagOperation": "==",
       "tagWord": "---",
       "tags": [
        { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
       ],
       "variable": "GCTimeRate"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "records consumer/producer rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "rec/sec" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - consumer",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "kafkaConsumerRecordsConsumedRate"
       }
      },
      {
       "_nsgTarget": {
        "alias": "$device - producer",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "kafkaProducersRecordSendRate"
       }
      }
     ]
    },
    {
     "title": "records size (avg/max)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "_nsgTarget": {
        "alias": "$device - avg",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
        "rawQuery": 0,
        "refId": "A",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "kafkaProducersRecordSizeAvg"
       }
      },
      {
       "_nsgTarget": {
        "alias": "$device - max",
        "columns": [
         {
          "appliedFunctions": [],
          "name": "metric",
          "visible": true
         },
         {
          "name": "time",
          "visible": false
         }
        ],
        "format": "time_series",
        "groupBy": { "type": "select type", "value": "select value" },
        "isTablePanel": false,
        "limit": 100,
        "orderBy": { "colName": "select value", "colValue": "select value", "column": { "alias": "", "name": "", "value": "" }, "sort": "ASC" },
        "rawQuery": 0,
        "refId": "B",
        "tags": [
         { "key": "NsgRole", "operator": "=", "value": "$NsgRole" }
        ],
        "type": "nsgql",
        "variable": "kafkaProducersRecordSizeMax"
       }
      }
     ]
    }
   ]
  }
 ]
}