name: SAST
on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:
    branches:
      - main
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  boost_security_sast:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/native-scanner
          api_token: ${{ secrets.BOOST_API_TOKEN }}